# Mode d'upload : 'api' ou 'ftp'
upload.mode=api

# Configuration API
api.url=http://localhost:8000/api/songs

# Configuration FTP
ftp.server=localhost
ftp.port=21
ftp.user=admin
ftp.pass=admin
ftp.dir=/Mp3
