-- ==========================================
-- STRUCTURE DE LA BASE DE DONNÉES
-- Générée depuis les entités Doctrine
-- ==========================================

-- ==========================================
-- Tables principales
-- ==========================================

CREATE TABLE t_user (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(180) NOT NULL,
    password VARCHAR(255) NOT NULL,
    roles JSON NOT NULL,
    nom VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT UNIQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE artiste (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE album (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    artist_id INT NOT NULL,
    release_date DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE song (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename VARCHAR(255) NOT NULL,
    title VARCHAR(255) DEFAULT NULL,
    duration INT NOT NULL,
    file_path VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE playlist (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    duree_totale INT NOT NULL,
    downloaded BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    id_user INT DEFAULT NULL,
    PRIMARY KEY (id)
);
CREATE INDEX IDX_D782112D6B3CA4B ON playlist (id_user);


-- ==========================================
-- Tables de liaison et index associés
-- ==========================================
CREATE TABLE t_song_artiste (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    song_id INT NOT NULL,
    artiste_id INT NOT NULL,
    PRIMARY KEY (song_id, artiste_id)
);
CREATE INDEX IDX_E63B45D2A0BDB2F3 ON t_song_artiste (song_id);
CREATE INDEX IDX_E63B45D221D25844 ON t_song_artiste (artiste_id);

CREATE TABLE t_song_genre (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    song_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (song_id, genre_id)
);
CREATE INDEX IDX_1AA19BCDA0BDB2F3 ON t_song_genre (song_id);
CREATE INDEX IDX_1AA19BCD4296D31F ON t_song_genre (genre_id);

CREATE TABLE t_playlist_song (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    playlist_id INT NOT NULL,
    song_id INT NOT NULL,
    PRIMARY KEY (playlist_id, song_id)
);
CREATE INDEX IDX_B6EC5C026BBD148 ON t_playlist_song (playlist_id);
CREATE INDEX IDX_B6EC5C02A0BDB2F3 ON t_playlist_song (song_id);

CREATE TABLE t_song_album (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    song_id INT NOT NULL,
    album_id INT NOT NULL,
    PRIMARY KEY (song_id, album_id)
);
CREATE INDEX IDX_A069C676A0BDB2F3 ON t_song_album (song_id);
CREATE INDEX IDX_A069C6761137ABCF ON t_song_album (album_id);

-- ==========================================
-- Contraintes de clés étrangères (Foreign Keys)
-- ==========================================

-- FK : album → artiste
ALTER TABLE album ADD CONSTRAINT FK_39986E43B7970CF8 FOREIGN KEY (artist_id) REFERENCES artiste (id) NOT DEFERRABLE;

-- FK : playlist → t_user
ALTER TABLE playlist ADD CONSTRAINT FK_D782112D6B3CA4B FOREIGN KEY (id_user) REFERENCES t_user (id) ON DELETE SET NULL NOT DEFERRABLE;

-- FK : t_song_album
ALTER TABLE t_song_album ADD CONSTRAINT FK_A069C676A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;
ALTER TABLE t_song_album ADD CONSTRAINT FK_A069C6761137ABCF FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE CASCADE;

-- FK : t_playlist_song
ALTER TABLE t_playlist_song ADD CONSTRAINT FK_B6EC5C026BBD148 FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE;
ALTER TABLE t_playlist_song ADD CONSTRAINT FK_B6EC5C02A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;

-- FK : t_song_artiste
ALTER TABLE t_song_artiste ADD CONSTRAINT FK_E63B45D2A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;
ALTER TABLE t_song_artiste ADD CONSTRAINT FK_E63B45D221D25844 FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE;

-- FK : t_song_genre
ALTER TABLE t_song_genre ADD CONSTRAINT FK_1AA19BCDA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;
ALTER TABLE t_song_genre ADD CONSTRAINT FK_1AA19BCD4296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;
