-- ==========================================
-- SCRIPT DE RÉINITIALISATION DE LA BASE
-- Générée depuis les entités Doctrine
-- ==========================================

-- 1. Suppression des tables existantes (CASCADE gère les FK)
DROP TABLE IF EXISTS t_song_categorie CASCADE;
DROP TABLE IF EXISTS t_song_genre CASCADE;
DROP TABLE IF EXISTS t_song_artiste CASCADE;
DROP TABLE IF EXISTS t_playlist_song CASCADE;
DROP TABLE IF EXISTS t_artiste_genre CASCADE;

DROP TABLE IF EXISTS song CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;
DROP TABLE IF EXISTS genre CASCADE;
DROP TABLE IF EXISTS categorie CASCADE;
DROP TABLE IF EXISTS artiste CASCADE;

-- 2. Création des tables principales
CREATE TABLE artiste (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE categorie (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE genre (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE playlist (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom VARCHAR(255) NOT NULL,
    duree_totale INT NOT NULL,
    downloaded BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE song (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    filename VARCHAR(255) NOT NULL,
    title VARCHAR(255) DEFAULT NULL,
    album VARCHAR(255) DEFAULT NULL,
    duration INT NOT NULL,
    file_path VARCHAR(500) DEFAULT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

-- ==========================================
-- Tables de liaison et index associés
-- ==========================================

CREATE TABLE t_artiste_genre (
    artiste_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (artiste_id, genre_id)
);
CREATE INDEX IDX_D261ACC721D25844 ON t_artiste_genre (artiste_id);
CREATE INDEX IDX_D261ACC74296D31F ON t_artiste_genre (genre_id);

CREATE TABLE t_playlist_song (
    playlist_id INT NOT NULL,
    song_id INT NOT NULL,
    PRIMARY KEY (playlist_id, song_id)
);
CREATE INDEX IDX_B6EC5C026BBD148 ON t_playlist_song (playlist_id);
CREATE INDEX IDX_B6EC5C02A0BDB2F3 ON t_playlist_song (song_id);

CREATE TABLE t_song_artiste (
    song_id INT NOT NULL,
    artiste_id INT NOT NULL,
    PRIMARY KEY (song_id, artiste_id)
);
CREATE INDEX IDX_E63B45D2A0BDB2F3 ON t_song_artiste (song_id);
CREATE INDEX IDX_E63B45D221D25844 ON t_song_artiste (artiste_id);

CREATE TABLE t_song_genre (
    song_id INT NOT NULL,
    genre_id INT NOT NULL,
    PRIMARY KEY (song_id, genre_id)
);
CREATE INDEX IDX_1AA19BCDA0BDB2F3 ON t_song_genre (song_id);
CREATE INDEX IDX_1AA19BCD4296D31F ON t_song_genre (genre_id);

CREATE TABLE t_song_categorie (
    song_id INT NOT NULL,
    categorie_id INT NOT NULL,
    PRIMARY KEY (song_id, categorie_id)
);
CREATE INDEX IDX_DD972963A0BDB2F3 ON t_song_categorie (song_id);
CREATE INDEX IDX_DD972963BCF5E72D ON t_song_categorie (categorie_id);

-- ==========================================
-- Contraintes de clés étrangères (Foreign Keys)
-- ==========================================

ALTER TABLE t_artiste_genre
    ADD CONSTRAINT FK_D261ACC721D25844
    FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE;

ALTER TABLE t_artiste_genre
    ADD CONSTRAINT FK_D261ACC74296D31F
    FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;

ALTER TABLE t_playlist_song
    ADD CONSTRAINT FK_B6EC5C026BBD148
    FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE;

ALTER TABLE t_playlist_song
    ADD CONSTRAINT FK_B6EC5C02A0BDB2F3
    FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;

ALTER TABLE t_song_artiste
    ADD CONSTRAINT FK_E63B45D2A0BDB2F3
    FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;

ALTER TABLE t_song_artiste
    ADD CONSTRAINT FK_E63B45D221D25844
    FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE;

ALTER TABLE t_song_genre
    ADD CONSTRAINT FK_1AA19BCDA0BDB2F3
    FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;

ALTER TABLE t_song_genre
    ADD CONSTRAINT FK_1AA19BCD4296D31F
    FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE;

ALTER TABLE t_song_categorie
    ADD CONSTRAINT FK_DD972963A0BDB2F3
    FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE;

ALTER TABLE t_song_categorie
    ADD CONSTRAINT FK_DD972963BCF5E72D
    FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE;
