<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618055609 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE artiste (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE t_artiste_genre (artiste_id INT NOT NULL, genre_id INT NOT NULL, PRIMARY KEY (artiste_id, genre_id))');
        $this->addSql('CREATE INDEX IDX_D261ACC721D25844 ON t_artiste_genre (artiste_id)');
        $this->addSql('CREATE INDEX IDX_D261ACC74296D31F ON t_artiste_genre (genre_id)');
        $this->addSql('CREATE TABLE categorie (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE genre (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE playlist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, duree_totale INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE t_playlist_song (playlist_id INT NOT NULL, song_id INT NOT NULL, PRIMARY KEY (playlist_id, song_id))');
        $this->addSql('CREATE INDEX IDX_B6EC5C026BBD148 ON t_playlist_song (playlist_id)');
        $this->addSql('CREATE INDEX IDX_B6EC5C02A0BDB2F3 ON t_playlist_song (song_id)');
        $this->addSql('CREATE TABLE t_song_artiste (song_id INT NOT NULL, artiste_id INT NOT NULL, PRIMARY KEY (song_id, artiste_id))');
        $this->addSql('CREATE INDEX IDX_E63B45D2A0BDB2F3 ON t_song_artiste (song_id)');
        $this->addSql('CREATE INDEX IDX_E63B45D221D25844 ON t_song_artiste (artiste_id)');
        $this->addSql('CREATE TABLE t_song_genre (song_id INT NOT NULL, genre_id INT NOT NULL, PRIMARY KEY (song_id, genre_id))');
        $this->addSql('CREATE INDEX IDX_1AA19BCDA0BDB2F3 ON t_song_genre (song_id)');
        $this->addSql('CREATE INDEX IDX_1AA19BCD4296D31F ON t_song_genre (genre_id)');
        $this->addSql('CREATE TABLE t_song_categorie (song_id INT NOT NULL, categorie_id INT NOT NULL, PRIMARY KEY (song_id, categorie_id))');
        $this->addSql('CREATE INDEX IDX_DD972963A0BDB2F3 ON t_song_categorie (song_id)');
        $this->addSql('CREATE INDEX IDX_DD972963BCF5E72D ON t_song_categorie (categorie_id)');
        $this->addSql('ALTER TABLE t_artiste_genre ADD CONSTRAINT FK_D261ACC721D25844 FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_artiste_genre ADD CONSTRAINT FK_D261ACC74296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_playlist_song ADD CONSTRAINT FK_B6EC5C026BBD148 FOREIGN KEY (playlist_id) REFERENCES playlist (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_playlist_song ADD CONSTRAINT FK_B6EC5C02A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_song_artiste ADD CONSTRAINT FK_E63B45D2A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_song_artiste ADD CONSTRAINT FK_E63B45D221D25844 FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_song_genre ADD CONSTRAINT FK_1AA19BCDA0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_song_genre ADD CONSTRAINT FK_1AA19BCD4296D31F FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_song_categorie ADD CONSTRAINT FK_DD972963A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE t_song_categorie ADD CONSTRAINT FK_DD972963BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE song DROP artist');
        $this->addSql('ALTER TABLE song DROP genre');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE t_artiste_genre DROP CONSTRAINT FK_D261ACC721D25844');
        $this->addSql('ALTER TABLE t_artiste_genre DROP CONSTRAINT FK_D261ACC74296D31F');
        $this->addSql('ALTER TABLE t_playlist_song DROP CONSTRAINT FK_B6EC5C026BBD148');
        $this->addSql('ALTER TABLE t_playlist_song DROP CONSTRAINT FK_B6EC5C02A0BDB2F3');
        $this->addSql('ALTER TABLE t_song_artiste DROP CONSTRAINT FK_E63B45D2A0BDB2F3');
        $this->addSql('ALTER TABLE t_song_artiste DROP CONSTRAINT FK_E63B45D221D25844');
        $this->addSql('ALTER TABLE t_song_genre DROP CONSTRAINT FK_1AA19BCDA0BDB2F3');
        $this->addSql('ALTER TABLE t_song_genre DROP CONSTRAINT FK_1AA19BCD4296D31F');
        $this->addSql('ALTER TABLE t_song_categorie DROP CONSTRAINT FK_DD972963A0BDB2F3');
        $this->addSql('ALTER TABLE t_song_categorie DROP CONSTRAINT FK_DD972963BCF5E72D');
        $this->addSql('DROP TABLE artiste');
        $this->addSql('DROP TABLE t_artiste_genre');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE genre');
        $this->addSql('DROP TABLE playlist');
        $this->addSql('DROP TABLE t_playlist_song');
        $this->addSql('DROP TABLE t_song_artiste');
        $this->addSql('DROP TABLE t_song_genre');
        $this->addSql('DROP TABLE t_song_categorie');
        $this->addSql('ALTER TABLE song ADD artist VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE song ADD genre VARCHAR(100) DEFAULT NULL');
    }
}
