<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260618085620 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE album (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE t_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, nom VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USER_EMAIL ON t_user (email)');
        $this->addSql('ALTER TABLE t_artiste_genre DROP CONSTRAINT fk_d261acc74296d31f');
        $this->addSql('ALTER TABLE t_artiste_genre DROP CONSTRAINT fk_d261acc721d25844');
        $this->addSql('DROP TABLE t_artiste_genre');
        $this->addSql('ALTER TABLE playlist ADD id_user INT DEFAULT NULL');
        $this->addSql('ALTER TABLE playlist ADD CONSTRAINT FK_D782112D6B3CA4B FOREIGN KEY (id_user) REFERENCES t_user (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D782112D6B3CA4B ON playlist (id_user)');
        $this->addSql('ALTER TABLE song ADD album_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE song DROP album');
        $this->addSql('ALTER TABLE song ADD CONSTRAINT FK_33EDEEA11137ABCF FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_33EDEEA11137ABCF ON song (album_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE t_artiste_genre (artiste_id INT NOT NULL, genre_id INT NOT NULL, PRIMARY KEY (artiste_id, genre_id))');
        $this->addSql('CREATE INDEX idx_d261acc721d25844 ON t_artiste_genre (artiste_id)');
        $this->addSql('CREATE INDEX idx_d261acc74296d31f ON t_artiste_genre (genre_id)');
        $this->addSql('ALTER TABLE t_artiste_genre ADD CONSTRAINT fk_d261acc74296d31f FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE t_artiste_genre ADD CONSTRAINT fk_d261acc721d25844 FOREIGN KEY (artiste_id) REFERENCES artiste (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE t_user');
        $this->addSql('ALTER TABLE playlist DROP CONSTRAINT FK_D782112D6B3CA4B');
        $this->addSql('DROP INDEX IDX_D782112D6B3CA4B');
        $this->addSql('ALTER TABLE playlist DROP id_user');
        $this->addSql('ALTER TABLE song DROP CONSTRAINT FK_33EDEEA11137ABCF');
        $this->addSql('DROP INDEX IDX_33EDEEA11137ABCF');
        $this->addSql('ALTER TABLE song ADD album VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE song DROP album_id');
    }
}
